sources:
  - name: Enel
    url: https://www.enel.com/careers

  - name: Ferrovie dello Stato
    url: https://fscareers.gruppofs.it

  - name: Poste Italiane
    url: https://www.posteitaliane.it/it/lavora-con-noi.html

  - name: Intesa Sanpaolo
    url: https://group.intesasanpaolo.com/it/careers

  - name: UniCredit
    url: https://www.unicreditgroup.eu/en/careers.html

  - name: Esselunga
    url: https://www.esselungajob.it
